# Generated by Django 3.1.1 on 2020-09-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('title',), 'verbose_name': 'Наша услуга', 'verbose_name_plural': 'Наши услуги'},
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='NoPhoto', upload_to='services/'),
        ),
    ]
