# Generated by Django 3.1.1 on 2020-09-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200911_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(default='NoPhoto', upload_to='customer/')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наши команды',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ContactClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('phone', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
            options={
                'verbose_name': 'Контакт клинта',
                'verbose_name_plural': 'Контакты клиентов',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='NoPhoto', upload_to='customer/')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='NoPhoto', upload_to='portfolio/')),
            ],
            options={
                'verbose_name': 'Наша работа',
                'verbose_name_plural': 'Наши работы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='NoPhoto', upload_to='price/')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайсы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(default='NoPhoto', upload_to='production/')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производствы',
                'ordering': ('title',),
            },
        ),
    ]
