# Generated by Django 3.1.1 on 2020-09-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_command_contactclient_customer_portfolio_price_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('name',), 'verbose_name': 'Наша команда', 'verbose_name_plural': 'Наши команды'},
        ),
        migrations.AlterModelOptions(
            name='contactclient',
            options={'ordering': ('name',), 'verbose_name': 'Контакт клинта', 'verbose_name_plural': 'Контакты клиентов'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RenameField(
            model_name='command',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactclient',
            name='title',
        ),
        migrations.AddField(
            model_name='contactclient',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='phone',
            field=models.DecimalField(decimal_places=2, max_digits=22, verbose_name='Номер телефона'),
        ),
    ]
