# Generated by Django 3.1.1 on 2020-09-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200911_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('-name',), 'verbose_name': 'Наша команда', 'verbose_name_plural': 'Наши команды'},
        ),
        migrations.AlterModelOptions(
            name='contactclient',
            options={'ordering': ('-name',), 'verbose_name': 'Контакт клинта', 'verbose_name_plural': 'Контакты клиентов'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('-title',), 'verbose_name': 'Наша работа', 'verbose_name_plural': 'Наши работы'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('-title',), 'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайсы'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ('-title',), 'verbose_name': 'Производство', 'verbose_name_plural': 'Производствы'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('-title',), 'verbose_name': 'Наша услуга', 'verbose_name_plural': 'Наши услуги'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='NoPhoto', upload_to='customer/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='NoPhoto', upload_to='portfolio/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наши работы'),
        ),
        migrations.AlterField(
            model_name='price',
            name='image',
            field=models.ImageField(default='NoPhoto', upload_to='price/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прайс'),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='production',
            name='image',
            field=models.ImageField(default='NoPhoto', upload_to='production/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='production',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Производство'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='NoPhoto', upload_to='services/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наши услуги'),
        ),
    ]
