# Generated by Django 3.1.1 on 2020-09-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200912_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactclient',
            name='phone',
            field=models.CharField(max_length=22, verbose_name='Номер телефона'),
        ),
    ]
